version: "3.8"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: nerd
      MYSQL_PASSWORD: dbs3cr3t
      MYSQL_DATABASE: bbuddytest
    ports:
      - 3306:3306
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=67108864
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  api:
    image: zbcjackson/bbuddy-java-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
      - 4000:4000
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
  frontend:
    image: zbcjackson/bbuddy-react
    ports:
      - 8100:80
    depends_on:
      - api